language: c

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

before_install:
    - .travis/before_install.sh

before_script:
    - .travis/before_script.sh

script:
    - .travis/script.sh

after_success:
    - ssh-agent .travis/after_success.sh

env:
    - BUILD_PLATFORM='unix' BUILD_MAKEPATH='build' BUILD_MAKEARGS='distcheck'

matrix:
    exclude:
        - os: osx
          compiler: gcc
    include:
        - os: linux
          compiler: gcc
          env: BUILD_PLATFORM='contiki' BUILD_MAKEPATH='contiki-src/examples/smcp-plugtest' BUILD_MAKEARGS='TARGET=minimal-net CONTIKI=../../../contiki'
        - os: linux
          compiler: gcc
          env: BUILD_PLATFORM='contiki' BUILD_MAKEPATH='contiki-src/examples/smcp-complex' BUILD_MAKEARGS='TARGET=native CONTIKI=../../../contiki'
        - os: linux
          compiler: gcc
          env: BUILD_PLATFORM='contiki' BUILD_MAKEPATH='contiki-src/examples/smcp-simple' BUILD_MAKEARGS='TARGET=minimal-net CONTIKI=../../../contiki'
